version: "3.2"

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./sya
    volumes:
      - './sya:/app/sya'
    ports:
        - 3333:3333
    command:
        yarn dev:server 
    environment:
        - DEBUG=sya:*
        - PORT=8080
    depends_on: 
      - db

  db:
    image: postgres
    volumes:
      - ./database/scripts:/docker-entrypoint-initdb.d
    #- ./database/postgresql/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
     - POSTGRES_PASSWORD=password
